Allow "weight: 0" in messages to mask them
axolotl-ai-cloud/axolotl pull request #1703
Opened 2024-06-11 14:16 UTC by DavidFarago

Allow in message objects the additional key `weight`, which can be set to 0 (or 1) to cause that message to be masked out (or left unmasked) for training (similar to [1]). This is helpful for training the model to be robust and capable of error recovery upon a bad assistant message. A missing `weight` key defaults to weight 1, to guarantee downward compatibility.

Extend `tests/prompt_strategies/test_sharegpt.py` to contain messages with `weight` keys.

Extend `src/axolotl/prompters.py::_build_result` to return the turns with weights as additional tuple element. Do this in axolotl directly instead of modifying `fastchat.conversation`'s `Conversation`.

Extend `src/axolotl/prompt_tokenizers.py::tokenize_prompt` to mask out tokens when weight is set to 0.

[1]: https://github.com/mistralai/mistral-finetune

# Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate)

## Types of changes

## Social Handles (Optional)

2024-06-12 14:06 UTC, winglian requested changes

2024-06-12 14:06 UTC, winglian commented on tests/prompt_strategies/test_sharegpt.py
Rather than modifying the existing test, could you leave that in place to test the prior feature capability and add a new test for the new feature?

2024-06-12 15:43 UTC, DavidFarago commented on tests/prompt_strategies/test_sharegpt.py
Good point, @winglian. I added 4 new test cases in the same file because the test cases are closely related.

2024-06-12 23:18 UTC, winglian approved these changes
thank you!

2024-06-13 06:49 UTC, DavidFarago commented
you are welcome, @winglian -- thank you for reviewing.

Will you merge this PR or give me write access to this repository?

2024-06-20 14:05 UTC, merged

2024-06-20 14:05 UTC, winglian commented
merged. thanks @DavidFarago !