Add ds model card
axolotl-ai-cloud/axolotl pull request #2094
Opened 2024-11-20 21:36 UTC by bursteratom

Continuation of PR#1015 with rebasing

# Description

Add dataset tagging to model card for both local and push to huggingface hub.

https://github.com/huggingface/hub-docs/blob/main/modelcard.md

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate)

## Types of changes

## Social Handles (Optional)

2024-11-20 21:39 UTC, bursteratom commented
@winglian this is a temporary WIP patch, the proper way will probably be actually parsing dataset_tags into the trainer for proper kwarg sanitising, I think. Do you think it's necessary?

2024-11-22 00:50 UTC, winglian commented
Why skip for dpo? Let's make sure to properly handle that case too.

2024-11-22 15:59 UTC, bursteratom commented
@winglian trl trainer's `def create_model_card()` has different arguments that don't seem to directly support dataset tags (it only allows you to parse the name of a single dataset),
https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py
so thinking of how to get around that properly

2024-11-24 12:58 UTC, winglian requested changes
there are too many unrelated changes in this PR from doing a merge commit. Please resolve and re-request a review.

2024-11-24 12:58 UTC, winglian commented on .github/workflows/pypi.yml
This file should have no edits, you have some errors in your merge commit. I personally prefer to rebase branches rather than merge commits to avoid issues like this.

2024-11-24 12:58 UTC, winglian commented on .gitignore
saem as above.

2024-11-24 12:58 UTC, winglian commented on docs/unsloth.qmd
saem as above.

2024-11-24 12:58 UTC, winglian commented on examples/colab-notebooks/colab-axolotl-example.ipynb
saem as above.

2024-11-24 12:58 UTC, winglian commented on requirements.txt
saem as above.

2024-11-24 12:58 UTC, winglian commented on scripts/unsloth_install.py
saem as above.

2024-11-24 19:32 UTC, bursteratom commented
to be continued with rebasing here: https://github.com/axolotl-ai-cloud/axolotl/pull/2101

2024-11-24 19:32 UTC, closed without merging